Initial commit for adding new lint for significant drops who may have…
PrestonFrom/rust pull request #1
Opened 2022-02-18 06:08 UTC by PrestonFrom

… surprising lifetimes

2022-02-20 10:25 UTC, oli-obk requested changes
While I have a few more things that we shoukd iterate on, (message text, more precise spans, documentation) I think we should merge it and then keep working on it in follow ups. This should put less of a burden on you and give everyone something to experiment with, even if it's not yet where we want it to be at the end

2022-02-20 10:25 UTC, oli-obk commented on library/core/src/marker.rs
> +#[stable(feature = "significant_drop", since = "1.60.0")]
Please make it unstable for now

2022-02-20 10:25 UTC, oli-obk commented on src/tools/clippy/clippy_lints/src/significant_drop_in_scrutinee.rs
> +}
You probably need to format these files, but I'm unsure how to do that in the clippy copy inside the rustc repo

2022-02-20 10:25 UTC, oli-obk commented on src/tools/clippy/clippy_lints/src/significant_drop_in_scrutinee.rs
> +        match expression.peel_drop_temps().kind {
Whoa, magic function, good find!

2022-02-20 10:25 UTC, oli-obk commented on src/tools/clippy/clippy_lints/src/significant_drop_in_scrutinee.rs
> +    "default lint description"
You forgot to fill in this placeholder

2022-02-21 03:13 UTC, PrestonFrom commented on library/core/src/marker.rs
> +#[stable(feature = "significant_drop", since = "1.60.0")]
Done!

2022-02-21 03:13 UTC, PrestonFrom commented on src/tools/clippy/clippy_lints/src/significant_drop_in_scrutinee.rs
> +}
I checked the clippy repo documentation, but I couldn't find anything on formatting, so I ran `cargo fmt`. I'm not sure if that will be satisfactory or not though.

2022-02-21 03:14 UTC, PrestonFrom commented on src/tools/clippy/clippy_lints/src/significant_drop_in_scrutinee.rs
> +        match expression.peel_drop_temps().kind {
:)

2022-02-21 03:14 UTC, PrestonFrom commented on src/tools/clippy/clippy_lints/src/significant_drop_in_scrutinee.rs
> +    "default lint description"
Oh! Thank you!

2022-02-21 03:15 UTC, PrestonFrom commented
Thank you for the initial review -- reviewing/merging an unstable version and iterating makes sense to me. I'll open a PR into the main repo.

2022-05-09 13:20 UTC, closed without merging